# Setup problem/game parameters before running the dlp_node
debug: False
# unique agent ID, starts from 0
myID: 0
# [rows, columns]
grid_size: [5,5]
# sector size (x,y) in ENU, in meter(s)
sector_size: [1, 1]
# origin shifts (dx,dy) from (0,0) in ENU, in meter(s)
origin_shifts: [0, 0]
N_defenders: 1
N_attackers: 1
# count of base sectors
nBase: 1
# set of base sectors 
Base: [1]
# count of base reference sectors
nBaseRef: 3
# set of base referense sectors
BaseRef: [2,6,7]
# strategy weights
alpha: -0.99
beta: -0.01
# prediction horizon
Tp: 2
neighbor_radius: 1
#d_start_locations
update_freq: 50
# home position
home: [1.0, 1.0]
# fixed altitude setpoint
altitude_setpoint: 1.0
# use joystick
enable_joystick: False
# whether to use GPS or directly local_position coordinates
use_gps: False
# lat/long of zero position
lat0: 47.397742
long0: 8.5455933
# fence
fence_min_x: 0.0
fence_max_x: 5.0
fence_min_y: 0.0
fence_max_y: 5.0
# attacker capture distance, [meter]
capture_distance: 1.5
