# Setup problem/game parameters before running the dlp_node
debug: False
# unique agent ID, starts from 0
myID: 0

# [rows, columns]
#grid_size: [7,7]
grid_size: [10,10]

# Grid four conrners
# Whether to use grid corners along with grid_size (sector_size will be computed automatically) or not
use_grid_corners: True
# Po: origin, PE: east corner, PN: north corner, PNE: north-east corner, w.r.t Po
grid_corner_Po: [47.397742, 8.5455933]
grid_corner_PE: [47.3977418, 8.5462601]
#grid_corner_PE: [47.3981254, 8.5457602]
grid_corner_PN: [47.3981923, 8.5455924]
grid_corner_PNE: [47.3981928, 8.5462601]

# sector size (x,y) in ENU, in meter(s)
# for hawrdware test
#sector_size: [0.85, 0.85]
#### for simulation
# for small world
#sector_size: [2.0, 2.0]
# for big world
#sector_size: [10.0, 10.0]
# for medium world
sector_size: [5.0, 5.0]

# origin shifts (dx,dy) from (0,0) in ENU, in meter(s)
##### for indoor hardware experiment at RISC lab
#origin_shifts: [3.0, 3.0]

##### for simulation
# for small /medium world
origin_shifts: [0.0, 0.0]
# for big world
#origin_shifts: [50.0, 50.0]

N_defenders: 3
N_attackers: 3

# count of base sectors
nBase: 1

# set of base sectors 
### For Gazebo simulation
# for small world
#Base: [11]

# for big world

#Base: [46]
# for medium world
Base: [35]

# count of base reference sectors
#nBaseRef: 3
#### For simulation in Gazebo

# for big world
#nBaseRef: 12

# for medium world
#nBaseRef: 7
# more obstacles
nBaseRef: 4
# with no obstacles
#nBaseRef: 8

# set of base referense sectors
#BaseRef: [2,8,9]
#BaseRef: [3,4,5,10,12,17,18,19]

# for big world
#BaseRef: [34,35,36,37,44,47,54,57,64,65,66,67]

# for medium world
#BaseRef: [25, 26, 34, 36, 44, 45, 46]
# more obstacles
BaseRef: [25, 34, 36, 45]
# with no obstacles
#BaseRef: [24, 25, 26, 34, 36, 44, 45, 46]

# Sector (and # of sectors) locations of static obstacles

#### For simulations in Gazebo
# for the big world
#Nobs_sectors: 10
#obs_sectors: [45,46,55,56, 74, 53, 58,77, 33,28]

# for the medium world
#Nobs_sectors: 5
#obs_sectors: [35, 33, 24, 47, 56]
# more obstacles
Nobs_sectors: 8
obs_sectors: [35, 33, 24, 26, 47, 56, 44, 46]
# with no obstacles, except the base
#Nobs_sectors: 1
#obs_sectors: [35]


# strategy weights
alpha: -0.99
beta: -0.01

# prediction horizon
Tp: 4

neighbor_radius: 1

# defenders global/local sensing of enemies
local_sensing: True

# local vs. global communication between defenders (centralized vs decomposed approach)
global_comms: False

# defenders velocity [m/s]
d_velocity: [4.0, 4.0, 4.0]

# use local estimates of all defenders states
use_local_estimates: True

# maximum ROS loop frequency
update_freq: 50

# home position
home: [1.0, 1.0]

# fixed altitude setpoint
altitude_setpoint: 3.0

# use joystick
enable_joystick: False

# whether to use GPS or directly local_position coordinates
# False for indoor hardware test
use_gps: True

# whether to used simulated position, set True if using gazebo
# False for hardware test
use_sim: True

# lat/long of zero position in Gazebo
# for small and medium worlds
lat0: 47.397742
long0: 8.5455933

# for big world
#lat0: 47.3972911
#long0: 8.5449276

# fence for simulation
# for small world
#fence_min_x: 0
#fence_max_x: 14.0
#fence_min_y: 0.0
#fence_max_y: 14.0

# for medium world
fence_min_x: 0.0
fence_max_x: 50.0
fence_min_y: 0.0
fence_max_y: 50.0

# for big world
#fence_min_x: -50.0
#fence_max_x: 50.0
#fence_min_y: -50.0
#fence_max_y: 50.0

# for hardware test
#fence_min_x: -2.8
#fence_max_x: 2.8
#fence_min_y: -2.0
#fence_max_y: 2.2

# attacker capture distance, [meter]
# for hardware test
#capture_distance: 1.2
# for simulation
# for small world
#capture_distance: 2.1

# for medium world
capture_distance: 7.1

# for big world
#capture_distance: 10.1

# if true, use algorithm to compute attack plan
# otherwise, joystick is expected to be used
auto_attack: true
